os: linux
dist: focal
language: ruby
services:
- docker
script:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker build -t voltairemc/terraswoopforce-server:latest .
- docker push voltairemc/terraswoopforce-server:latest
env:
  global:
  - secure: ZnG7COVQeFu7dLwnvBRa2D8sQy64kZEUq39RHMbUZ9OCGuLrdIuJaBjgXWIA8Bc4uDoBlX/eDx3xdL1s91Q/o7StQyQLsq0PPx78Y4mv+8ca9yQ0MsGOc6Ux0UpBe0WRaNWoUAeMME6NaezPpIK1Y4KeeHSLDV2+j+9L3wdVukqpl+kCy7PRmkUfue2bclYvDxVsIhzmZNVXe0JxdbWm5aLnIvI7LY73XglKvzaGvpyESev2cm++2uv/hrpUOAMY8FnAO+kFOebJFL9ZI8DNm9PaC+ybfjF2chYRkHndoJUYvGAYwBZV1NNC2GCsbZ0fk6FsWS3ahuyyZzTaViwHvWes7pJm2zwiFI9jvxKlS1Cbe5Rhb0jW7bn1FOFYV6AO+QyXJoFDNssdpYvAJUxSxLTjPfvUC+ral1rxDTjXn64RKK39ZKu23BkCTqJO0iE5FbetZ6aMRC3HUfLJl34xgSLm4Ype3vB3YdqfHjc1cGtPSjshtsqeGK4LNw1y3zET16/x+tbST6UkxY0DKVg29vlPtjnbBfU1P5fyh2gDNSEu25NEK/9KefKS791aM73BCupSzFO6uOspEKgDbwLCrJFS0IN3ZDaW2XOXwqhC6Mr4oF+2agimXX8ge2VXWayjTuE/M2oeJFfzLJcpcMpIpqFrPVsHuemEDDwU5gjMibg=
  - secure: RWcq15sEoNBbMMNYnI905sXkit293Sf+gfFkG87jyT7y4KY+UIXtCWvOkj7oe4RdMA+W+rv+vJ+3NR+ln2ghEdxqPbnB4ngT9N41deY5lRltimYwNrpIgYSFPZjxbelul0Kle27fTy/Q7+WWQmQCQVjEOyqDluA1IdONKpNKzdnLfQb+NjKSJYrXTySZnhnhMPoxSxx/Leojcmoe+KtSLpbRbeQxOZIaPaYpkdMNtWB9qO2RI8G25UTA4kRG0lx8ncouv791/AQKD5v3vA4sZqI7d9QlLf/YyeZsxCoCPjkd+FK4+czC9lwd7V7vC1EcplKIhBw+PmniqZxmIEneLS/yREEz+QI8z9CceEHe4gzFfbdkqqON0GVpELrvHQRAPboq6uBqgSJpVG7sLbC6V/FE5phjqLjrPpU9kITnjW9B2ziYt8REPmeuTA5SjoiZi7yFWfF+ySG1mXg351tf+piB7hsr/FldORumpBPkqeS16yqWoeKnUJle+hfCLmQH5Q7Z6v925yzLc7iqLWQIpPLs7IrR0EYXoE54yHV0hdeGngDxL+x1d2PVJ5ScscaK2dGIxbgwc33f0fDQrz3EjhslVagCjqLSTxEMfAraRlRUY5LvHIEHe5eIJX+TnS5+Z40TmKjgbeuylagSM+kqjFKzfA6cZtLj1NV49n35ViY=
